CREATE TABLE IF NOT EXISTS pengaduan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  lokasi VARCHAR(255) NOT NULL,
  deskripsi TEXT NOT NULL,
  file_media VARCHAR(255) DEFAULT NULL,
  tanggal_laporan DATETIME DEFAULT CURRENT_TIMESTAMP
);
